- name: Remove unwanted packaged
  apt: name={{item}} state=absent
  with_items:
    - account-plugin-facebook
    - account-plugin-twitter
    - unity-lens-music
    - unity-lens-photos
    - unity-lens-shopping
    - unity-lens-video

- name: Add extra repositories
  apt_repository: repo={{item}}
  with_items:
    - ppa:webupd8team/java

- name: Install extra packages
  apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - chromium-browser
    - icedtea-7-plugin
    - oracle-jdk7-installer
    - terminator
    - vim-gtk
    - wireshark

- name: Install language support
  apt: name={{item}} state=present
  with_items:
    - hunspell-en-ca
    - hyphen-en-us
    - language-pack-gnome-pt
    - language-pack-pt
    - libreoffice-help-en-gb
    - libreoffice-help-pt
    - libreoffice-help-pt-br
    - libreoffice-l10n-en-gb
    - libreoffice-l10n-en-za
    - libreoffice-l10n-pt
    - libreoffice-l10n-pt-br
    - myspell-en-au
    - myspell-en-gb
    - myspell-en-za
    - myspell-pt
    - mythes-en-au
    - mythes-en-us
    - openoffice.org-hyphenation
    - wbrazilian
    - wbritish
    - wportuguese
