# -*- mode: ruby -*-
# vi: set ft=ruby :

# If necessary resize the disk, do the following:
#   VBoxManage clonehd  ubuntu.vmdk ubuntu.vdi -format vdi -variant Standard
#   VBoxManage modifyhd ubuntu.vdi --resize 81920
#
# And inside the guest host:
#    sudo resize2fs /dev/sda1

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/artful64"
  config.vm.box_check_update = false

  config.vm.network :forwarded_port, guest:   80, host:   80, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest:  443, host:  443, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 8000, host: 8000, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 8086, host: 8086, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 8443, host: 8443, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 8983, host: 8983, host_ip: "127.0.0.1"

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  if Vagrant.has_plugin?("vagrant-proxyconf")
     config.proxy.http = "http://user:passwd@proxy.trt13.jus.br:8080"
     config.proxy.https = config.proxy.http
     config.proxy.ftp = config.proxy.http
     config.proxy.no_proxy = "localhost,127.0.0.1,10.13.0.0/16"
  end

  config.vm.provision "shell", path: "provision.sh", args: "desktop-minimal"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "4096"
    vb.customize ["setextradata", :id, "GUI/ShowMiniToolBar", "false"]
    vb.customize ["setextradata", :id, "GUI/Input/AutoCapture", "false"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"] 
  end

end
